### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by jontobonto** [Iapetus-11/better-statcord.py#5]
The example for [cogs](https://github.com/Iapetus-11/betterstatcord.py/blob/main/examples/example_cog.py) is not working anymore. 

```
Statcord stat posting error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/statcord/client.py", line 103, in _post_loop
    await self.post_stats()
  File "/usr/local/lib/python3.8/dist-packages/statcord/client.py", line 169, in post_stats
    raise Exception(f"Statcord server response status was not 200 OK:\n{await resp.text()}")
Exception: Statcord server response status was not 200 OK:
{"error":true,"message":"Custom 1 Parameter(s) are Missing or in the Wrong Format. (0). API Docs --> https://docs.statcord.com/#/api?id=post-bot-stats"}
```

**Comment by jontobonto** [comment]
First, I just tried this: 
```py
    def __init__(self, bot):
        self.bot = bot
        self.statcord_client = StatcordClient(bot, "statcord.com-TOKEN")

    def cog_unload(self):
        self.statcord_client.close()
```

After that I also tried this:

```py
    def __init__(self, bot):
        self.bot = bot
        self.statcord_client = StatcordClient(bot, "statcord.com-TOKEN", self.custom_graph_1)

    def cog_unload(self):
        self.statcord_client.close()

    async def custom_graph_1(self):
        return 1 + 2 + 3
```

**Comment by Iapetus-11** [comment]
I believe I have fixed this in `1.5.2`. Please let me know if there's still an issue.

**Comment by NarmyOnDiscord** [comment]
Sadly it's still not working.

**Comment by jontobonto** [comment]
Yea, now its working. Thanks. :D
